# Generated by Django 4.1.7 on 2023-04-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
