# Generated by Django 4.1.7 on 2023-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
